name: Build Dylib
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos Directly
        run: |
          export THEOS=/Users/runner/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH

      - name: Compile IzanagiV16
        run: make

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Izanagi-Dylib
          path: .theos/obj/debug/IzanagiV16.dylib
